Traceback (most recent call last):
  File "mSMSE_hd_m=400.py", line 331, in <module>
    L = int(L_seq[taskId])
IndexError: index 9 is out of bounds for axis 0 with size 9
